version: 2

updates:
  - package-ecosystem: "gradle"
    directories:
      - "/extlibs"
      - "/extlibs/.."
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directories:
      - "/"
    schedule:
      interval: "daily"
