version: 2

registries:
  google-maven:
    type: maven-repository
    url: https://dl.google.com/dl/android/maven2/

updates:
  - package-ecosystem: "gradle"
    directories:
      - "/extlibs"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directories:
      - "/"
    schedule:
      interval: "daily"
    registries:
      - google-maven
