version: 2

updates:
  - package-ecosystem: "gradle"
    directories:
      - "/extlibs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/libs"
    schedule:
      interval: "weekly"
